### ISSUE TITLE
Entity.setObject3D` was called with an object that was not an instance of THREE.Object3D.

### ISSUE THREAD

**Issue by Aupuma** [remmel/aframe-volograms#1]
Hi, I am trying to adapt  your library to work with 8thWall, but when setting the mesh I get this error:
`core:a-node:error Failure loading node:   Error: `Entity.setObject3D` was called with an object that was not an instance of THREE.Object3D.`

I am importing the volograms-js as a node module and referencing the Vologram class from the module in the component as:
`import { Vologram } from 'volograms-js' `
So maybe is due to using different THREE versions. I tried using the aframe-volograms script but gave me multiple errors with Three and Webpack. Do you know how could I get it working?

**Comment by remmel** [comment]
Hi, if you are using Vologram object directly and importing from 'volograms-js', maybe you should directly use https://github.com/remmel/volograms-js / https://www.npmjs.com/package/volograms-js and not use that current aframe repo. Have you already tried it?

**Comment by Aupuma** [comment]
Yes, the volograms-js class that I am using is the one from volograms-js module and not the aframe one

**Comment by Aupuma** [comment]
Finally, got it working! Just had to comment out the `import * as THREE from 'three'`, as AFrame already imports Three!
